name: Semantic Release

on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: 'Release type'
        required: true
        default: 'patch'
        options:
          - 'major'
          - 'minor'
          - 'patch'
      environment:
        type: choice
        description: 'Environment'
        required: true
        default: 'production'
        options:
          - 'production'
          - 'staging'
          - 'development'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      